# CleanConnect Pro Enhanced - Yarn Configuration
# Modern Yarn configuration for optimal performance

nodeLinker: node-modules

# Enable PnP mode for better performance (optional)
# nodeLinker: pnp

# Package extensions for better compatibility
packageExtensions:
  "*":
    peerDependenciesMeta:
      "*":
        optional: true

# Enable zero-installs for faster CI/CD
enableGlobalCache: true

# Enable telemetry (optional)
enableTelemetry: false

# Network settings
httpTimeout: 60000
httpRetry: 3

# Cache settings
enableMirror: true
enableProgress: true

# Logging
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

# Workspace settings
workspaceConcurrency: 4

# Plugins (if needed)
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#     spec: "@yarnpkg/plugin-workspace-tools"