#!/bin/bash
# Setup Cron Jobs for Full Automation
set -euo pipefail

AUTOMATION_DIR="$HOME/ai-sites/automation"

echo "⏰ Setting up Cron Automation"
echo "======================================"
echo ""

# Create cron job entries
CRON_FILE=$(mktemp)

cat > "$CRON_FILE" << 'EOF'
# Steven's Automated Creative Empire
# Generated by setup_cron_automation.sh

# Load environment
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
HOME=/Users/steven

# === DAILY AUTOMATION ===

# Daily Content Generation (8 AM)
0 8 * * * cd ~/ai-sites/automation/api-powered && python3 auto_content_pipeline.py daily >> ~/ai-sites/automation/logs/daily_content.log 2>&1

# Daily AI Art (9 AM)
0 9 * * * cd ~/ai-sites/automation/api-powered && python3 dalle_auto_generator.py daily >> ~/ai-sites/automation/logs/daily_art.log 2>&1

# Daily Backup (2 AM)
0 2 * * * ~/ai-sites/automation/quick-wins/auto_backup.sh >> ~/ai-sites/automation/logs/backup.log 2>&1

# Daily Stats Summary (6 PM)
0 18 * * * ~/ai-sites/automation/quick-wins/stats.sh > ~/ai-sites/automation/logs/daily_stats.log 2>&1

# === CONTENT GENERATION (Every 4 hours) ===

# Recipe Generation (10 AM, 2 PM, 6 PM)
0 10,14,18 * * * cd ~/ai-sites/content-management/retention-hub/recipes && python3 generate_recipe.py >> ~/ai-sites/automation/logs/recipes.log 2>&1

# === WEEKLY AUTOMATION ===

# Weekly Music Sampler (Monday 10 AM)
0 10 * * 1 cd ~/ai-sites/content-management/retention-hub/weekly-music && python3 generate_weekly_playlist.py >> ~/ai-sites/automation/logs/weekly_music.log 2>&1

# Weekly Performance Report (Monday 9 AM)
0 9 * * 1 cd ~/ai-sites/automation/performance && python3 feedback_loop.py --report 7 >> ~/ai-sites/automation/logs/performance.log 2>&1

# Weekly Revenue Summary (Sunday 6 PM)
0 18 * * 0 cd ~/ai-sites/automation/revenue-dashboard && python3 dashboard.py > ~/ai-sites/automation/logs/revenue_weekly.log 2>&1

# === SOCIAL MEDIA (Every 6 hours) ===

# Auto-generate social posts (6 AM, 12 PM, 6 PM)
0 6,12,18 * * * cd ~/ai-sites/automation/api-powered && python3 ai_content_generator.py social "$(shuf -n1 ~/ai-sites/automation/api-powered/topics.txt)" >> ~/ai-sites/automation/logs/social.log 2>&1

EOF

echo "📋 Cron jobs to be added:"
echo "=========================="
cat "$CRON_FILE"
echo ""
echo "=========================="
echo ""

# Create topics file for random topic selection
cat > "$AUTOMATION_DIR/api-powered/topics.txt" << 'EOF'
AI in creative industries
music production tips
digital art techniques
passive income strategies
content automation
sustainable living
productivity hacks
mindfulness practices
creative inspiration
technology trends
EOF

echo "✅ Created topics file for variety"
echo ""

read -p "Add these cron jobs to your crontab? (y/n): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
  # Backup existing crontab
  crontab -l > "$HOME/ai-sites/automation/logs/crontab_backup_$(date +%Y%m%d_%H%M%S).txt" 2>/dev/null || echo "# New crontab" > /dev/null

  # Add new jobs
  (crontab -l 2>/dev/null; cat "$CRON_FILE") | crontab -

  echo "✅ Cron jobs installed!"
  echo ""
  echo "View active jobs:"
  echo "  crontab -l"
  echo ""
  echo "View logs:"
  echo "  tail -f ~/ai-sites/automation/logs/daily_content.log"
  echo "  tail -f ~/ai-sites/automation/logs/daily_art.log"
  echo ""
  echo "Remove jobs:"
  echo "  crontab -e"
else
  echo ""
  echo "📄 Cron jobs saved to: $CRON_FILE"
  echo "💡 Install manually with: crontab $CRON_FILE"
fi

# Create log directory
mkdir -p "$AUTOMATION_DIR/logs"

echo ""
echo "======================================"
echo "⏰ Your Empire Will Now Run on Autopilot!"
echo ""
echo "Schedule:"
echo "  • Daily: Content (8AM), Art (9AM), Backup (2AM), Stats (6PM)"
echo "  • Every 4hrs: Recipes (10AM, 2PM, 6PM)"
echo "  • Weekly: Music (Mon 10AM), Reports (Mon 9AM), Revenue (Sun 6PM)"
echo "  • Every 6hrs: Social posts (6AM, 12PM, 6PM)"
echo ""
echo "Monitor:"
echo "  ~/ai-sites/automation/logs/"
