# n8n AI Agent Docker Compose
# ===========================
# Complete AI automation stack with n8n, AI agent server, and content research
# Based on your existing Docker starters with AI enhancements

version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
      - POSTGRES_USER=${POSTGRES_USER:-n8n}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./n8n-data/backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-n8n} -d ${POSTGRES_DB:-n8n}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-agent-network

  # n8n Workflow Automation
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-ai-agent
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5678:5678"
    environment:
      - TZ=${TZ:-America/New_York}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/New_York}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SECURE_COOKIE=true
      - N8N_PROXY_HOPS=1
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # AI Agent Integration
      - AI_AGENT_URL=http://ai-agent:5000
      - CONTENT_RESEARCH_URL=http://ai-agent:5000
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_workflows:/home/node/.n8n/workflows
      - ./local-files:/files
      - ./n8n-data/logs:/home/node/.n8n/logs
    networks:
      - ai-agent-network

  # AI Agent Server
  ai-agent:
    build:
      context: /Users/steven
      dockerfile: Dockerfile.ai-agent
    container_name: ai-agent-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Core AI APIs
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      
      # Audio & Music APIs
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - SUNO_COOKIE=${SUNO_COOKIE}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      
      # Art & Vision APIs
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - RUNWAY_API_KEY=${RUNWAY_API_KEY}
      - LEONARDO_API_KEY=${LEONARDO_API_KEY}
      
      # Automation & Agents APIs
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      
      # Documents & Knowledge APIs
      - NOTION_TOKEN=${NOTION_TOKEN}
      
      # SEO & Analytics APIs
      - SERPAPI_KEY=${SERPAPI_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      
      # Server Configuration
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - LOG_LEVEL=INFO
      - N8N_WEBHOOK_URL=http://n8n:5678
    volumes:
      - /Users/steven/Documents:/app/documents:ro
      - /Users/steven/.env.d:/app/.env.d:ro
      - ai_agent_data:/app/data
      - ai_agent_logs:/app/logs
    networks:
      - ai-agent-network
    depends_on:
      - n8n

  # Content Research Agent
  content-research:
    build:
      context: /Users/steven
      dockerfile: Dockerfile.content-research
    container_name: content-research-agent
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCUMENTS_PATH=/app/documents
      - RESEARCH_OUTPUT_PATH=/app/research
      - LOG_LEVEL=INFO
    volumes:
      - /Users/steven/Documents:/app/documents:ro
      - content_research_data:/app/research
      - content_research_logs:/app/logs
    networks:
      - ai-agent-network

  # Redis for Caching (Optional)
  redis:
    image: redis:7-alpine
    container_name: n8n-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-agent-network

  # Monitoring with Prometheus (Optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: n8n-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - ai-agent-network

  # Grafana for Dashboards (Optional)
  grafana:
    image: grafana/grafana:latest
    container_name: n8n-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - ai-agent-network

volumes:
  n8n_data:
  pg_data:
  ai_agent_data:
  ai_agent_logs:
  content_research_data:
  content_research_logs:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  ai-agent-network:
    driver: bridge