import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = {
  js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit:
https://github.com/QuantumForgeLabs
*/`
};

const isWatch = process.argv.includes("--watch");

const context = await esbuild.context({
  banner,
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
    "@codemirror/language", "@codemirror/lint", "@codemirror/search", "@codemirror/state",
    "@codemirror/view", "@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (isWatch) {
  await context.watch();
  console.log("Vault Ops Toolkit: watching for changes...");
} else {
  await context.rebuild();
  await context.dispose();
  console.log("Vault Ops Toolkit: build complete.");
}
